image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
<<<<<<< HEAD
    EXEC: huff
    HW_DIR: hw1
=======
    EXEC: dtmf
    HW_DIR: hw2
>>>>>>> HW2_CODE/master
    CPU_LIMIT: 60
    FILE_LIMIT: 1000000
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
    - run
    - test
build:
    stage: build
    script:
        - echo "Build done"
run:
    stage: run
    script:
        - ulimit -t ${CPU_LIMIT}
        - ulimit -f ${FILE_LIMIT}
<<<<<<< HEAD
        - cd ${HW_DIR} && bin/${EXEC} -h
=======
        - cd ${HW_DIR} && bin/${EXEC} -d < rsrc/dtmf_all.au

>>>>>>> HW2_CODE/master
test:
    stage: test
    script:
        - ulimit -t ${CPU_LIMIT}
        - ulimit -f ${FILE_LIMIT}
<<<<<<< HEAD
        - cd ${HW_DIR} && bin/${EXEC}_tests -S --verbose=0 --timeout 30
=======
        - cd ${HW_DIR} && bin/${EXEC}_tests -S --verbose=0 -j1 --timeout 30
>>>>>>> HW2_CODE/master
